=== InseeFr/Queen-Back-Office/queen-application/src/main/resources/static/v3/schema.interrogation-temp-zone.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Interrogation temp zone schema",
  "description": "Validation of interrogation temp zone",
  "type": "object",
  "additionalProperties": false,
  "required": ["data", "stateData", "questionnaireId"],
  "properties": {
    "data": {
      "$ref": "schema.data.json#"
    },
    "comment": {
      "type": "object"
    },
    "personalization": {
      "$ref": "schema.personalization.json#"
    },
    "questionnaireId": {
      "type": "string",
      "minLength": 1
    },
    "stateData": {
      "$ref": "#/$defs/stateData"
    }
  },
  "$defs": {
    "stateData": {
      "type": "object",
      "required": ["date", "state", "currentPage"],
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": "number"
        },
        "state": {
          "enum": ["INIT", "COMPLETED", "VALIDATED", "TOEXTRACT", "EXTRACTED"]
        },
        "currentPage": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}

=== InseeFr/Queen-Back-Office/queen-application/src/test/resources/data/json-schema-validation/surveyunittempzone/valid-tempzone.json
{
  "data": {
    "EXTERNAL": {
      "BOOLEAN_VAR": false,
      "NULL_VAR": null,
      "STRING_VAR": "string",
      "NUM_VAR": 1,
      "ARRAY_BOOLEAN": [true, false],
      "ARRAY_NULL": [null, null],
      "ARRAY_STRING": ["string", "string"],
      "ARRAY_NUM": [1, 2]
    },
    "CALCULATED": {
      "BOOLEAN_VAR": false,
      "NULL_VAR": null,
      "STRING_VAR": "string",
      "NUM_VAR": 1,
      "ARRAY_BOOLEAN": [true, false],
      "ARRAY_NULL": [null, null],
      "ARRAY_STRING": ["string", "string"],
      "ARRAY_NUM": [1, 2]
    },
    "COLLECTED": {
      "VALUE": {
        "EDITED": false,
        "FORCED": null,
        "INPUTED": "string",
        "COLLECTED": 1
      },
      "ARRAY": {
        "EDITED": [true, false],
        "FORCED": [null, null],
        "INPUTED": ["string", "string"],
        "PREVIOUS": [1, 2],
        "INPUTTED": "string"
      }
    }
  },
  "comment": {
    "commentaire": "hello"
  },
  "stateData": {
    "state": "EXTRACTED",
    "date": 123456789,
    "currentPage": "2.3"
  },
  "questionnaireId": "QUESTIONNAIRE-1"
}
